HospitalManagement.Web/HospitalManagement.Web/Controllers/StaffController.cs
using HospitalManagement.Web.Models;
using HospitalManagement.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HospitalManagement.Web.Controllers
{
    public class StaffController : Controller
    {
        HospitalManagementContext _context = new HospitalManagementContext();
        Staff_Category cat = new Staff_Category();
        // GET: Staff
        public ActionResult Index()
        {
            int count = _context.StaffCategory.Count(x => x.CategoryName == "Nurse");
            if (count == 0)
            {
                Staff_Category Category = new Staff_Category();
                Category.Updated = DateTime.Now;
                Category.UpdatedBy = "Auto Generated";
                Category.CategoryName = "Nurse";
                _context.StaffCategory.Add(Category); _context.SaveChanges();
                Category.CategoryName = "Ward Boy";
                _context.StaffCategory.Add(Category); _context.SaveChanges();
                Category.CategoryName = "Accountant";
                _context.StaffCategory.Add(Category); _context.SaveChanges();
                Category.CategoryName = "Janitor";
                _context.StaffCategory.Add(Category); _context.SaveChanges();
                Category.CategoryName = "Admin";
                _context.StaffCategory.Add(Category); _context.SaveChanges();
                Category.CategoryName = "Guard";
                _context.StaffCategory.Add(Category); _context.SaveChanges();

            }
            List<Staff_Category> Categoryl = _context.StaffCategory.ToList();
            ViewBag.CategoryList = new SelectList(Categoryl, "CategoryName", "CategoryName");

            DateTime tt = DateTime.Parse("11/11/2000");
            var model = _context.Staffs.Where(x=>x.RetireDate==tt).ToList();
            return View(model);
        }

        public JsonResult GetList(string Category)
        {

            _context.Configuration.ProxyCreationEnabled = false;
            List<Staff> List = _context.Staffs.Where(x => x.Designation == Category).ToList();
            return Json(List, JsonRequestBehavior.AllowGet);
        }


        public ActionResult RetiredList()
        {
            DateTime tt = DateTime.Parse("11/11/2000");
            var model = _context.Staffs.Where(x => x.RetireDate != tt).ToList();
            return View(model);
        }

        // GET: Staff/Details/5
        public ActionResult Details(int id)
        {
            DateTime tt = DateTime.Parse("11/11/2000");
            var model = _context.Staffs.Find(id);
            int chk=0;
            if (model.RetireDate == tt) chk = 1;
            ViewBag.chk = chk;
            return View(model);
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            List<Staff_Category> Category = _context.StaffCategory.ToList();
            ViewBag.CategoryList = new SelectList(Category, "CategoryName", "CategoryName");
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        public ActionResult Create(Staff collection)
        {
            try
            {
                // TODO: Add insert logic here
                collection.Updated = DateTime.Today;
                collection.UpdatedBy = User.Identity.Name;
                
                DateTime tt =  DateTime.Parse("11/11/2000");
                collection.RetireDate = tt;
                _context.Staffs.Add(collection);_context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Staff/Edit/5
        public ActionResult Edit(int id)
        {
            List<Staff_Category> Category = _context.StaffCategory.ToList();
            ViewBag.CategoryList = new SelectList(Category, "CategoryName", "CategoryName");

            var model = _context.Staffs.Find(id);
            return View(model);
        }

        // POST: Staff/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Staff collection)
        {
            try
            {
                // TODO: Add update logic here
                Staff Staff = new Staff();
                Staff.Name = collection.Name;
                Staff.Contact = collection.Contact;
                Staff.ContactNo = collection.ContactNo;
                Staff.ContactEmail = collection.ContactEmail;
                Staff.Salary = collection.Salary;
                Staff.Designation = collection.Designation;
                Staff.joinningDate = collection.joinningDate;
                Staff.Updated = DateTime.Today;
                Staff.UpdatedBy = User.Identity.Name;

                _context.Entry(Staff).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Staff/Delete/5
        public ActionResult Delete(int id)
        {
            var model = _context.Staffs.Find(id);
            return View(model);
        }

        // POST: Staff/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, Staff collection)
        {
            try
            {
                // TODO: Add delete logic here
                Staff staff = _context.Staffs.Find(id);
                staff.RetireDate = collection.RetireDate;
                staff.Updated = DateTime.Now;
                staff.UpdatedBy = User.Identity.Name;

                _context.Entry(staff).State = System.Data.Entity.EntityState.Modified;
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/Create.cshtml
@model HospitalManagement.Data.Staff

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model=>model.Designation, ViewBag.CategoryList as SelectList,"--- Select Category--", new {@class = "form-control" })
                @*@Html.EditorFor(model => model.Designation, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.joinningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.joinningDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.joinningDate, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.RetireDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RetireDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RetireDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.IssuedBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssuedBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssuedBy, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/Delete.cshtml
@model HospitalManagement.Data.Staff

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


   
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />

        <div>
           
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Contact)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Contact)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactNo)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactNo)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ContactEmail)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ContactEmail)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Salary)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Salary)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Designation)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Designation)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.joinningDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.joinningDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RetireDate)
                </dt>

                <dd>
                    @Html.EditorFor(model => model.RetireDate, new { htmlAttributes = new { @class = "form-control" } })
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IssuedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IssuedBy)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Updated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Updated)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UpdatedBy)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UpdatedBy)
                </dd>

            </dl>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Retire Him/Her" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/Details.cshtml
@model HospitalManagement.Data.Staff

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Staff</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.joinningDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.joinningDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RetireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RetireDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IssuedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IssuedBy)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UpdatedBy)
        </dd>

    </dl>
</div>
<p>
    @{
        if (ViewBag.chk == 0)
        {
            @Html.ActionLink("Back to List", "RetiredList")
        }
        else
        {
           @Html.ActionLink("Edit", "Edit", new { id = Model.Id }); <br />
               @Html.ActionLink("Back to List", "Index")
        };
    }
   
</p>

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/Edit.cshtml
@model HospitalManagement.Data.Staff

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Staff</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Designation, ViewBag.CategoryList as SelectList, "--- Select Category--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.joinningDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.joinningDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.joinningDate, "", new { @class = "text-danger" })
            </div>
        </div>

        



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/Index.cshtml
@model IEnumerable<HospitalManagement.Data.Staff>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Add Staff", "Create")| | @Html.ActionLink("Staff Category","Index","StaffCategory") ||  @Html.ActionLink("Show Retired Staffs", "RetiredList", "Staff")
</p>
<div class="form-group">
    <div class="col-md-10">
        @Html.DropDownList("Designation", ViewBag.CategoryList as SelectList, "--- Select Category--", new { @class = "form-control" })
    </div>
</div>


    <table id="tb" class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Contact)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.joinningDate)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.RetireDate)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.IssuedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Updated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdatedBy)
            </th>
            <th></th>
        </tr>


        @foreach (var item in Model)
        {
            <tr >
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Contact)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.joinningDate)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.RetireDate)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.IssuedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Updated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UpdatedBy)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Retire Staff", "Delete", new { id = item.Id })
                </td>
            </tr>
        }



    </table>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script>
        $(document).ready(function () {
           
            $("#Designation").change(function () {
                 $("#tb").empty();
                $.get("/Staff/GetList", { Category: $("#Designation").val() }, function (data) {
                    var row;
                   row += "<tr><th>" + "Name" + "</th><th>" + "Contact" + "</th><th>" + "ContactNo" + "</th><th>" + "ContactEmail" + "</th><th>" + "Salary" + "</th><th>" + "Designation" + "</th><th>" + "joinningDate" + "</th><th>" + "IssuedBy" + "</th><th>" + "Updated" + "</th><th>" + "UpdatedBy" + "</th><th>" + '<a href="link">' + "</th></tr>"
                    $.each(data, function (i, item) {
                        var MyDate_String_Value = item.joinningDate;
                         var value = new Date( parseInt(MyDate_String_Value.replace(/(^.*\()|([+-].*$)/,'')) );
                        var dat = value.getMonth() +1 +"/" +value.getDate() +"/" +  value.getFullYear();

                        var MyDate = item.Updated;
                        var val = new Date(parseInt(MyDate.replace(/(^.*\()|([+-].*$)/, '')));
                        var Update = val.getMonth() + 1 + "/" + val.getDate() + "/" + val.getFullYear();
                        row += "<tr><td>" + item.Name + "</td><td>" + item.Contact + "</td><td>" + item.ContactNo + "</td><td>" + item.ContactEmail + "</td><td>" + item.Salary + "</td><td>" + item.Designation + "</td><td>" + dat + "</td><td>" + item.IssuedBy + "</td><td>" + Update + "</td><td>" + item.UpdatedBy + "</td><td>" + '<a href="/Staff/Edit/' + item.Id + '">Edit</a> ||<a href="/Staff/Details/' + item.Id + '">Details</a> | |<a href="/Staff/Delete/' + item.Id + '">Retire</a>' + "</td></tr>"
                    });
                    $("#tb").append(row);
                });

            })
        });
    </script>
    @**@

HospitalManagement.Web/HospitalManagement.Web/Views/Staff/RetiredList.cshtml
@model IEnumerable<HospitalManagement.Data.Staff>

@{
    ViewBag.Title = "RetiredList";
}

<h2>RetiredList</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Contact)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactNo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactEmail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Salary)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Designation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.joinningDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RetireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssuedBy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UpdatedBy)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Contact)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactEmail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Salary)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Designation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.joinningDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RetireDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IssuedBy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Updated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UpdatedBy)
        </td>
        <td>
            
            @Html.ActionLink("Details", "Details", new { id=item.Id }) 
           
        </td>
    </tr>
}

</table>